using System;
using RoR2;
using Unity;

namespace GOTCE.Misc {
    public enum Tier : int
    {
        F = 0,
        D = 1,
        C = 2,
        B = 3,
        A = 4,
        S = 5
    }
    public class Woolie {
        public static Dictionary<ItemDef, Tier> TierMap;

        public static void Initialize() {
                TierMap = new() {
                    {RoR2Content.Items.AlienHead, Tier.B},
                    {RoR2Content.Items.ArmorPlate, Tier.B},
                    {RoR2Content.Items.ArmorReductionOnHit, Tier.S},
                    {RoR2Content.Items.AttackSpeedOnCrit, Tier.A},
                    {RoR2Content.Items.AutoCastEquipment, Tier.S},
                    {RoR2Content.Items.Bandolier, Tier.C},
                    {RoR2Content.Items.BarrierOnKill, Tier.A},
                    {RoR2Content.Items.BarrierOnOverHeal, Tier.D},
                    {RoR2Content.Items.Bear, Tier.S},
                    {RoR2Content.Items.BeetleGland, Tier.D},
                    {RoR2Content.Items.Behemoth, Tier.S},
                    {RoR2Content.Items.BleedOnHit, Tier.A},
                    {RoR2Content.Items.BleedOnHitAndExplode, Tier.S},
                    {RoR2Content.Items.BonusGoldPackOnKill, Tier.A},
                    {RoR2Content.Items.BoostAttackSpeed, Tier.A},
                    {RoR2Content.Items.BounceNearby, Tier.A},
                    {RoR2Content.Items.CaptainDefenseMatrix, Tier.S},
                    {RoR2Content.Items.ChainLightning, Tier.S},
                    {RoR2Content.Items.Clover, Tier.S},
                    {RoR2Content.Items.CrippleWardOnLevel, Tier.C},
                    {RoR2Content.Items.CritGlasses, Tier.S},
                    {RoR2Content.Items.Crowbar, Tier.C},
                    {RoR2Content.Items.Dagger, Tier.B},
                    {RoR2Content.Items.DeathMark, Tier.A},
                    {RoR2Content.Items.EnergizedOnEquipmentUse, Tier.B},
                    {RoR2Content.Items.EquipmentMagazine, Tier.A},
                    {RoR2Content.Items.ExecuteLowHealthElite, Tier.A},
                    {RoR2Content.Items.ExtraLife, Tier.C},
                    {RoR2Content.Items.KillEliteFrenzy, Tier.A},
                    {RoR2Content.Items.FallBoots, Tier.A},
                    {RoR2Content.Items.Feather, Tier.S},
                    {RoR2Content.Items.FireballsOnHit, Tier.A},
                    {RoR2Content.Items.FireRing, Tier.A},
                    {RoR2Content.Items.Firework, Tier.C},
                    {RoR2Content.Items.FlatHealth, Tier.C},
                    {RoR2Content.Items.FocusConvergence, Tier.A},
                    {RoR2Content.Items.GhostOnKill, Tier.C},
                    {RoR2Content.Items.GoldOnHit, Tier.B},
                    {RoR2Content.Items.HeadHunter, Tier.C},
                    {RoR2Content.Items.HealOnCrit, Tier.S},
                    {RoR2Content.Items.HealWhileSafe, Tier.B},
                    {RoR2Content.Items.Hoof, Tier.S},
                    {RoR2Content.Items.IceRing, Tier.S},
                    {RoR2Content.Items.Icicle, Tier.B},
                    {RoR2Content.Items.IgniteOnKill, Tier.B},
                    {RoR2Content.Items.IncreaseHealing, Tier.A},
                    {RoR2Content.Items.Infusion, Tier.B},
                    {RoR2Content.Items.Knurl, Tier.C},
                    {RoR2Content.Items.LaserTurbine, Tier.A},
                    {RoR2Content.Items.LightningStrikeOnHit, Tier.S},
                    {RoR2Content.Items.LunarBadLuck, Tier.D},
                    {RoR2Content.Items.LunarDagger, Tier.C},
                    {RoR2Content.Items.LunarPrimaryReplacement, Tier.C},
                    {RoR2Content.Items.LunarSecondaryReplacement, Tier.A},
                    {RoR2Content.Items.LunarUtilityReplacement, Tier.C},
                    {RoR2Content.Items.LunarSpecialReplacement, Tier.A},
                    {RoR2Content.Items.LunarTrinket, Tier.C},
                    {RoR2Content.Items.Medkit, Tier.A},
                    {RoR2Content.Items.Missile, Tier.S},
                    {RoR2Content.Items.MonstersOnShrineUse, Tier.B},
                    {RoR2Content.Items.Mushroom, Tier.C},
                    {RoR2Content.Items.NearbyDamageBonus, Tier.C},
                    {RoR2Content.Items.NovaOnHeal, Tier.C},
                    {RoR2Content.Items.NovaOnLowHealth, Tier.C},
                    {RoR2Content.Items.ParentEgg, Tier.C},
                    {RoR2Content.Items.Pearl, Tier.D},
                    {RoR2Content.Items.PersonalShield, Tier.C},
                    {RoR2Content.Items.Plant, Tier.C},
                    {RoR2Content.Items.RandomDamageZone, Tier.C},
                    {RoR2Content.Items.RepeatHeal, Tier.D},
                    {RoR2Content.Items.RoboBallBuddy, Tier.C},
                    {RoR2Content.Items.SecondarySkillMagazine, Tier.A},
                    {RoR2Content.Items.Seed, Tier.C},
                    {RoR2Content.Items.ShieldOnly, Tier.C},
                    {RoR2Content.Items.ShinyPearl, Tier.A},
                    {RoR2Content.Items.ShockNearby, Tier.S},
                    {RoR2Content.Items.SlowOnHit, Tier.C},
                    {RoR2Content.Items.SprintArmor, Tier.C},
                    {RoR2Content.Items.SprintBonus, Tier.A},
                    {RoR2Content.Items.SprintOutOfCombat, Tier.C},
                    {RoR2Content.Items.SprintWisp, Tier.A},
                    {RoR2Content.Items.Squid, Tier.D},
                    {RoR2Content.Items.StickyBomb, Tier.B},
                    {RoR2Content.Items.StunChanceOnHit, Tier.C},
                    {RoR2Content.Items.Syringe, Tier.A},
                    {RoR2Content.Items.Talisman, Tier.A},
                    {RoR2Content.Items.Thorns, Tier.B},
                    {RoR2Content.Items.TitanGoldDuringTP, Tier.C},
                    {RoR2Content.Items.Tooth, Tier.B},
                    {RoR2Content.Items.TPHealingNova, Tier.D},
                    {RoR2Content.Items.TreasureCache, Tier.B},
                    {RoR2Content.Items.UtilitySkillMagazine, Tier.A},
                    {RoR2Content.Items.WarCryOnMultiKill, Tier.B},
                    {RoR2Content.Items.WardOnLevel, Tier.C},
                    {DLC1Content.Items.AttackSpeedAndMoveSpeed, Tier.A}, // dlc items
                    {DLC1Content.Items.BearVoid, Tier.A},
                    {DLC1Content.Items.BleedOnHitVoid, Tier.A},
                    {DLC1Content.Items.ChainLightningVoid, Tier.S},
                    {DLC1Content.Items.CloverVoid, Tier.C},
                    {DLC1Content.Items.CritDamage, Tier.A},
                    {DLC1Content.Items.CritGlassesVoid, Tier.S},
                    {DLC1Content.Items.DroneWeapons, Tier.C},
                    {DLC1Content.Items.ElementalRingVoid, Tier.A},
                    {DLC1Content.Items.EquipmentMagazineVoid, Tier.A},
                    {DLC1Content.Items.ExplodeOnDeathVoid, Tier.B},
                    {DLC1Content.Items.ExtraLifeVoid, Tier.S},
                    {DLC1Content.Items.FragileDamageBonus, Tier.S},
                    {DLC1Content.Items.FreeChest, Tier.S},
                    {DLC1Content.Items.GoldOnHurt, Tier.C},
                    {DLC1Content.Items.HalfAttackSpeedHalfCooldowns, Tier.C},
                    {DLC1Content.Items.HalfSpeedDoubleHealth, Tier.D},
                    {DLC1Content.Items.HealingPotion, Tier.B},
                    {DLC1Content.Items.ImmuneToDebuff, Tier.C},
                    {DLC1Content.Items.LunarSun, Tier.S},
                    {DLC1Content.Items.MinorConstructOnKill, Tier.C},
                    {DLC1Content.Items.MissileVoid, Tier.S},
                    {DLC1Content.Items.MoreMissile, Tier.S},
                    {DLC1Content.Items.MoveSpeedOnKill, Tier.B},
                    {DLC1Content.Items.MushroomVoid, Tier.S},
                    {DLC1Content.Items.OutOfCombatArmor, Tier.A},
                    {DLC1Content.Items.PermanentDebuffOnHit, Tier.S},
                    {DLC1Content.Items.PrimarySkillShuriken, Tier.S},
                    {DLC1Content.Items.RandomEquipmentTrigger, Tier.B},
                    {DLC1Content.Items.RandomlyLunar, Tier.C},
                    {DLC1Content.Items.RegeneratingScrap, Tier.A},
                    {DLC1Content.Items.SlowOnHitVoid, Tier.B},
                    {DLC1Content.Items.TreasureCacheVoid, Tier.A},
                    {DLC1Content.Items.StrengthenBurn, Tier.C},
                    {DLC1Content.Items.VoidMegaCrabItem, Tier.A}
                };
        }
    }
}